#ifndef ADT_H
#define ADT_H

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include "./liststatik/liststatik.h"
#include "./liststatik/liststatik.c"
#include "./listdin/listdin.h"
#include "./listdin/listdin.c"
#include "./wordmachine/wordmachine.h"
#include "./wordmachine/wordmachine.c"
#include "./wordmachine/charmachine.h"
#include "./wordmachine/charmachine.c"
#include "./time/datetime.h"
#include "./time/datetime.c"
#include "./time/time.h"
#include "./time/time.c"
#include "./stack/stack.h"
#include "./stack/stack.c"
#include "./queue/queue.h"
#include "./queue/queue.c"
#include "./matrix/matrix.h"
#include "./matrix/matrix.c"
#include "./matrix/matrix.h"
#include "./listlinier/listlinier.h"
#include "./listlinier/listlinier.c"
#include "./graf/graf.h"
#include "./graf/graf.c"
#include "./pcolor/pcolor.h"
#include "./pcolor/pcolor.c"
#include "./prioqueuefren/prioqueuefren.h"
#include "./prioqueuefren/prioqueuefren.c"
#include "./tree/tree.h"
#include "./tree/tree.c"

#endif